// <auto-generated />
using System;
using CW21.Presentation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CW21.Presentation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521123547_AddBookAndPublisher")]
    partial class AddBookAndPublisher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CW21.Presentation.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1952, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "USA",
                            FullName = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1976, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "UK",
                            FullName = "Jon Skeet"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1986, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "USA",
                            FullName = "James Clear"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 700m,
                            PublishYear = 2008,
                            Stock = 0,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 850m,
                            PublishYear = 2019,
                            Stock = 0,
                            Title = "C# In Depth"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 450m,
                            PublishYear = 2018,
                            PublisherId = 1,
                            Stock = 0,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 900m,
                            PublishYear = 1999,
                            PublisherId = 3,
                            Stock = 0,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 500m,
                            PublishYear = 2016,
                            PublisherId = 2,
                            Stock = 0,
                            Title = "Deep Work"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 550m,
                            PublishYear = 1500,
                            PublisherId = 4,
                            Stock = 5,
                            Title = "maktab"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 600m,
                            PublishYear = 15000,
                            PublisherId = 1,
                            Stock = 6,
                            Title = "maktab2"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 700m,
                            PublishYear = 2000,
                            PublisherId = 1,
                            Stock = 7,
                            Title = "maktab3"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 750m,
                            PublishYear = 2010,
                            PublisherId = 2,
                            Stock = 0,
                            Title = "maktab4"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 760m,
                            PublishYear = 2025,
                            PublisherId = 1,
                            Stock = 0,
                            Title = "maktab5"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Programming and software engineering books",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Personal growth books",
                            Name = "Self Development"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Focus and productivity books",
                            Name = "Productivity"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "mosko",
                            CreatedAt = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "dastayofski",
                            PhoneNumber = "9125846565"
                        },
                        new
                        {
                            Id = 2,
                            City = "tehran",
                            CreatedAt = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "mohamad",
                            PhoneNumber = "9125846565"
                        },
                        new
                        {
                            Id = 3,
                            City = "shiraz",
                            CreatedAt = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "akbari",
                            PhoneNumber = "9125846565"
                        },
                        new
                        {
                            Id = 4,
                            City = "tehran",
                            CreatedAt = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "roham",
                            PhoneNumber = "9125846565"
                        });
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Book", b =>
                {
                    b.HasOne("CW21.Presentation.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CW21.Presentation.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CW21.Presentation.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
